# Generated by Django 4.2.1 on 2023-08-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="wholesale",
            field=models.ManyToManyField(blank=True, to="product.wholesale"),
        ),
    ]
