# Generated by Django 4.2.1 on 2023-08-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_product_profile_alter_category_main_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wholesale",
            old_name="price_from",
            new_name="count_from",
        ),
        migrations.RenameField(
            model_name="wholesale",
            old_name="price_to",
            new_name="count_to",
        ),
        migrations.RemoveField(
            model_name="wholesale",
            name="product_count",
        ),
        migrations.AddField(
            model_name="wholesale",
            name="price",
            field=models.BigIntegerField(default=0),
        ),
    ]
