# Generated by Django 4.2.1 on 2023-08-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_rename_price_from_wholesale_count_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="wholesale",
            field=models.ManyToManyField(
                blank=True, related_name="product_wholesale", to="product.wholesale"
            ),
        ),
    ]
