# Generated by Django 4.2.1 on 2023-08-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_product_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tag",
        ),
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(to="product.tag"),
        ),
    ]
