# Generated by Django 4.2.1 on 2023-08-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_remove_product_tag_product_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tax",
            field=models.BigIntegerField(default=0),
        ),
    ]
