# Generated by Django 4.2.1 on 2023-08-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_product_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
