# Generated by Django 4.2.1 on 2023-08-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_order_user_delete_usercart"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserKupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
