# Generated by Django 4.2.1 on 2023-08-23 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_userkupon"),
        ("product", "0012_kupon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userkupon",
            name="kupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.kupon"
            ),
        ),
        migrations.AddField(
            model_name="userkupon",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
